### ISSUE TITLE
请问验证用户token失败后的处理

### ISSUE THREAD

**Issue by fakeshadow** [rustlang-cn/ruster#17]
直接返回一个future result是不是更好些，比如
`Err(_) => Box::new(FutureResult(Ok(HttpResponse::InternalServerError().into())))`

**Comment by krircc** [comment]
你可以尝试一下， 把 https://github.com/rustlang-cn/ruster/blob/master/src/api/user.rs#L28
替换你的比如
Err(_) => Box::new(FutureResult(Ok(HttpResponse::InternalServerError().into())))

**Comment by fakeshadow** [comment]
试了下，可以编译但是并没有实际测试。
https://github.com/fakeshadow/ruster/commit/8e01fdbef4a5fb47cb6fb775c8b344d7860cb194

**Comment by krircc** [comment]
应该是可以的，Thanks, 如果你愿意可以提个PR，不然我自己做了

**Comment by fakeshadow** [comment]
没测过，就不PR了，怕出什么问题。
多谢你的源码，对我这种新手学习很有益
