### ISSUE TITLE
改进建议

### ISSUE THREAD

**Issue by chenge** [rustlang-cn/ruster#6]
我发帖告诉我没有类别，然后内容全部丢掉了。

默认设置类别和标题，避免丢掉内容。

另外一点，减小输入区域最好在一页内，避免滚动。

**Comment by krircc** [comment]
是的，发帖前要切记选择好你的类别，不然提交提示不成功，内容不会缓存。

**Comment by chenge** [comment]
> 是的，发帖前要切记选择好你的类别，不然提交提示不成功，内容不会缓存。全屏情况下就是在一页内吧

真的不能发，今天又试了一次Firefox，没有提示。

**Comment by krircc** [comment]
好的，马上看一下，谢谢提示
